spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/EliteGear}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:P4ssword!}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/Elite-Gear
  docker:
    compose:
      lifecycle-management: start-only
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      CustomerEmailUnique: CUSTOMER_EMAIL_UNIQUE
      CustomerPhoneNumberUnique: CUSTOMER_PHONE_NUMBER_UNIQUE
      OrderPaymentUnique: ORDER_PAYMENT_UNIQUE
      OrderShippingUnique: ORDER_SHIPPING_UNIQUE
springdoc:
  pathsToMatch: /, /api/**

keycloak:
  auth-server-url: http://localhost:8081
  realm: Elite-Gear
  client-id: Elite-Gear
  client-secret: mgQ8X0lKWgi0M6Fxc9ezOmbPnBmtYlQT
  admin:
    username: admin
    password: 12345


stripe:
  secret:
    key: sk_test_51QKG2bCmGq871jAEaUwWAqLQdLQzHflVtP5khHAhQFwPEr6q71VwZhFa4uI4FYGLs8csyA0j9eWAq8xLimLREGBU002iDZ7DhK


#this is tests